### ISSUE TITLE
Can't find package segway_config

### ISSUE THREAD

**Issue by jonbinney** [StanleyInnovation/segway_v3_robot#1]
The segway_bringup package has a dependency on the segway_config package in its `package.xml`, but I can't seem to find the segway_config package. Should it instead depend on segway_v3_config? Or should that dependency be removed?

**Comment by PatrickHussey** [comment]
Yes sorry I need to update. It was renamed to segway_v3_config

**Comment by jonbinney** [comment]
I'm hacking on this right now anyway, so I'll send you a PR that fixes it.

**Comment by jonbinney** [comment]
PR submitted
