### ISSUE TITLE
Power button back to default state

### ISSUE THREAD

**Issue by hm-sarah** [StanleyInnovation/segway_v3_robot#11]
Hello,

We asked before to power the segway (RMP 220 v3) without pushing the power button. And you suggested to start the system by connecting 5V to the USB input temporarily through a switch. And it worked perfectly.

We want now to return the segway back to the factory default state, and turn it on from the initial push button (next to connector I). We removed the added switch, but the segway is not powering on when the push button is pressed.

Any idea how we can solve this issue.

NB: The auxiliary battery LED status was Red

Thanks.

**Comment by PatrickHussey** [comment]
Please contact info@stanleyinnovation.com for hardware support. This area is really meant for software
