### ISSUE TITLE
Joysitck error. Cannot control RMP with joystick.

### ISSUE THREAD

**Issue by somebodyus** [StanleyInnovation/segway_v3_robot#9]
I set USE joystick to true. I have tested the joystick OK using jstest.

After I run the command:
roslaunch segway_bringup stanley_innovation_system.launch 

The following errors pop up:

```
bad callback: <bound method SegwayTeleop._segway_teleop of <segway.segway_teleop.SegwayTeleop instance at 0x7f4dc59cd518>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/user/segway_ws/src/segway_v3/segway_ros/src/segway/segway_teleop.py", line 205, in _segway_teleop
    self._parse_joy_input(joyMessage)
  File "/home/user/segway_ws/src/segway_v3/segway_ros/src/segway/segway_teleop.py", line 173, in _parse_joy_input
    if item['set_val'] == joyMessage.buttons[item['index']]:
IndexError: tuple index out of range
```

How can I control RMP with joystick?

**Comment by PatrickHussey** [comment]
You need to set the joystick type in segway_config.sh:

xbox360: Logitech F310 or F360 (press mode button until LED is not lit for directx) or an xbox360 controller for Windows 

extreme3D: Logitech Extreme 3D Pro

Or you can making you own mapping in segway_bringup/launch/teleop/config

To test just run the joy node and echo the topic /joy to make sure it is reading inputs correctly

**Comment by somebodyus** [comment]
Thank you so much.
I changed it to xbox360, errors disappeared.

When I press the B button, the system goes into the tractor mode.  However, it continues to beep beep beep and does not respond to any joystick command.

**Comment by PatrickHussey** [comment]
You accidentally pressed the decel to zero speed (DTZ) button. It is the upper left trigger button. You were probably going for the deadman which is the lower left trigger (on the bottom of the controller).

In order to get it out of that mode you need to power cycle the machine. A software DTZ request is latching (ie no way to undo it unless you power down and power back on).

**Comment by somebodyus** [comment]
Thank you so much for your rapid and contributive reply.

I am using a Xbox style joystick. When I move the left joystick, the system has a sound but does not move.

**Comment by somebodyus** [comment]
Problem solved by simultaneously press LT and stick.

**Comment by PatrickHussey** [comment]
Yes LT is the deadman, needs to be pressed to command motion.
